### ISSUE TITLE
PaLM is not a constructor

### ISSUE THREAD

**Issue by alokid** [EvanZhouDev/palm-api#1]
![image](https://github.com/EvanZhouDev/palm-api/assets/138843462/8d699110-3e98-4db3-b1e2-0c62fe2d38e7)

**Comment by EvanZhouDev** [comment]
Looking into it...

**Comment by EvanZhouDev** [comment]
Can you show me how you are importing it?

It should be just `import PaLM from "palm-api"`

**Comment by alokid** [comment]
![image](https://github.com/EvanZhouDev/palm-api/assets/138843462/517d2e98-bf61-419e-88a9-e26c35aa573a)
@EvanZhouDev

**Comment by EvanZhouDev** [comment]
... what is that?

It may be because you are doing dynamic import wrong?

**Comment by alokid** [comment]
![image](https://github.com/EvanZhouDev/palm-api/assets/138843462/7f040f12-6b82-45ba-a6a4-d904f1e496b3)
I use await import in the bard-ai module, but the palm-api module is difficult.

**Comment by EvanZhouDev** [comment]
It's hard to say what's wrong... can you start a blank project and see what happens?

**Comment by alokid** [comment]
![image](https://github.com/EvanZhouDev/palm-api/assets/138843462/df8c6a28-e608-4cc4-ab08-c9ef45afb0f8)
I use a project that uses ESM, the module works

**Comment by EvanZhouDev** [comment]
But what about a blank project with Dynamic Import?

**Comment by alokid** [comment]
Yes, I used the empty Import project

**Comment by EvanZhouDev** [comment]
Does it not work that way?

**Comment by alokid** [comment]
it's just that, the first one I use CJS but it doesn't work or use await import. the second one works after using ESM

**Comment by EvanZhouDev** [comment]
Did you manage to fix it?

**Comment by Specifix5** [comment]
```ts
const importDynamic = new Function('modulePath', 'return import(modulePath)')
const PaLM = (await importDynamic("palm-api")).default
``` 
try adding .default if you are using CommonJS, works for me!
