### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Crystal-Spider** [EvanZhouDev/palm-api#2]
I'm trying to use this API in a TypeScript strict project.

I try to import `PaLM` by doing `import {PaLM} from 'palm-api';`, however this gives the following error:

> Could not find a declaration file for module 'palm-api'. '.../node_modules/palm-api/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/palm-api` if it exists or add a new declaration (.d.ts) file containing `declare module 'palm-api';` ts(7016)

The command `npm i --save-dev @types/palm-api` gives E404.

Would it be possible to add support for TypeScript?

**Comment by sr-04** [comment]
I don't think we have a module named palm-api. We can access API using get method which is different from downloading a module.

**Comment by Crystal-Spider** [comment]
But in your readme there is an example to import it: `import PaLM from "palm-api";`

Never mind that in my previous comment there are curly brackets around `PaLM`, the error is the same regardless.  
What I believe to be the issue is that this API only supports plain JavaScript; TypeScript strict then gives off an error because there are no types in the module, and so everything would be `any`.

**Comment by EvanZhouDev** [comment]
Yes, I am aware that we currently do not have TypeScript support. You are welcome to add it yourself through a pull request (PR). I have a number of other tasks on my plate at the moment, so I may not be able to address it immediately. Apologies for any inconvenience! 😅

**Comment by Crystal-Spider** [comment]
Sure thing, do you have any code-style rules you'd like me to follow?

**Comment by EvanZhouDev** [comment]
Nope, do whatever you are comfortable with. Thank you so much!

**Comment by Crystal-Spider** [comment]
In [this section](https://github.com/EvanZhouDev/palm-api#palmembed), is this correct?
> Any model capable of `generateText`. Default: `embedding-gecko-001`.

Shouldn't it say `embedText`?

**Comment by EvanZhouDev** [comment]
Ah, you got me there... it is 😅

**Comment by Crystal-Spider** [comment]
I'm basically done, I just need to check if I configured everything correctly to be packaged with npm and still work properly, but I'm going to do it tomorrow since it's now 01:30 am where I live ahah

**Comment by EvanZhouDev** [comment]
No worries, take your time...

**Comment by Crystal-Spider** [comment]
I opened a PR: #3

**Comment by EvanZhouDev** [comment]
Wow, this is amazingly done... higher quality than anything I could ship 🤣

Honestly, I was just expecting .d.ts file, but this is better! I'm assuming you've tested everything?

**Comment by Crystal-Spider** [comment]
Unfortunately I couldn't test because I'm still on the waiting list for PaLM API and MakerSuite :/  
Theoretically, no working should have changed, as all the work I did was mainly to add types. Of course I do agree that testing it out would be better ahah  
What I'm actually unsure is whether I correctly setup the project to be published and used by others, but I wouldn't know how to test this.

**Comment by Crystal-Spider** [comment]
Do you think you can find the time to test it out, merge the PR, and release a new version?

**Comment by Crystal-Spider** [comment]
Hello! Any update on this? Unfortunately I still haven't been granted access to the PaLM API.

**Comment by Crystal-Spider** [comment]
Hello! Any update on this? Unfortunately I still haven't been granted access to the PaLM API.
