### ISSUE TITLE
TypeError: Found non-callable @@iterator

### ISSUE THREAD

**Issue by Sidharth004** [EvanZhouDev/palm-api#4]
Error:
Scenario - while using createChat method as shown in documentation.

Issue: - TypeError: Found non-callable @@iterator

The createChat() method in the PaLM API is expecting an object as argument, not an iterable. So, there seems to be a mistake in the implementation of the createChat method in the version of the PaLM API you're using. It's trying to spread rawConfig as if it was an iterable, but it's actually an object.

possible way to temporarily fix this :
by passing an array
![image](https://github.com/EvanZhouDev/palm-api/assets/89736536/b6618d6d-c753-4fa5-a953-a1b40b0cb0bf)

**Comment by EvanZhouDev** [comment]
This appears to be fine on my side. Check again on version 1.1.0, please.

**Comment by EvanZhouDev** [comment]
Closing. If needed, please reopen :)
