### ISSUE TITLE
No inputs found in config file

### ISSUE THREAD

**Issue by Crystal-Spider** [EvanZhouDev/palm-api#5]
Hi, it's me again, I found out a problem with my TypeScript port that I couldn't have caught before having my hands on the real published package.  
Luckily the fix should be very easy, it's just needed to exclude the tsconfig.json file from the published package. To do so there should be two ways:

1. Add a "files" entry in your package.json like `"files": "out"`
2. Add a .npmignore file and inside it write `tsconfig.json`

Personally I'd go with option 1.

Thank you again!

**Comment by Crystal-Spider** [comment]
Also, not very relevant to this specific issue, but would it be possible to export the `Chat` class too?

**Comment by EvanZhouDev** [comment]
Fixed in `1.1.1`... as for the second issue, isn't it [already a thing](https://github.com/EvanZhouDev/palm-api?tab=readme-ov-file#palmcreatechat)?

**Comment by Crystal-Spider** [comment]
Nope. I mean, I can use it, but I can't import the type.

**Comment by EvanZhouDev** [comment]
Feel free to submit a PR for this issue, I am very unfamiliar with Typescript 😅
